Removed SNplot duplicate
RECETOX/MFAssignR pull request #27
Opened 2023-12-12 13:38 UTC by hechth

Closes #8 

Removed the SNplot function from HistNoise and added a test that creates the plot.
Also ran `devtools::document` to create the NAMESPACE file automatically.

2023-12-12 15:07 UTC, zargham-ahmad commented on MFAssignR/tests/testthat/test-KMDNoise.R
> +  load("../../data/Raw_Neg_ML.rda")
```suggestion
  load(system.file("data", "Raw_Neg_ML.rda",
    package = "MFAssignR",
    mustWork = TRUE
  ))
```

2023-12-12 15:08 UTC, zargham-ahmad commented on MFAssignR/tests/testthat/test-KMDNoise.R
> +  load("../../data/Raw_Neg_ML.rda")
```suggestion
  load(system.file("data", "Raw_Neg_ML.rda",
    package = "MFAssignR",
    mustWork = TRUE
  ))
```

2023-12-13 08:36 UTC, KristinaGomoryova requested changes

2023-12-13 08:36 UTC, KristinaGomoryova commented on MFAssignR/tests/testthat/test-KMDNoise.R
> +  head(Raw_Neg_ML)
```suggestion
```

remove the head() please

2023-12-13 08:37 UTC, KristinaGomoryova approved these changes

2023-12-13 08:43 UTC, merged