Functions from FindRecalSeries.R exported
RECETOX/MFAssignR pull request #51
Opened 2024-09-09 12:02 UTC by KristinaGomoryova

This PR deals with exporting the functions from FindRecalSeries.R, as well as documents them and adds the functions to the namespace.

2024-09-10 12:18 UTC, hechth commented
Please remove the .Rd files from the PR as we don't want to check them in :)

2024-09-10 12:19 UTC, hechth requested changes
Please remove the .Rd files - otherwise looks good :)

2024-09-11 07:59 UTC, KristinaGomoryova commented
resolved in 2f8f328bd371c6e1623f9d20c968ae862e3b9c24 ; but I deleted only the files incoming with this PR, we shall keep the other Rd files in here?

2024-09-11 09:27 UTC, hechth approved these changes

2024-09-11 12:53 UTC, merged